name: DEXDonate
version: ${project.version}
main: ru.ocelotjungle.dexdonate.DEXDonate
description: Make your donate smarter
commands:
  dexd:
    description: main command
    usage: /dexd help
    permission: dexdonate.basic
    aliases: [dexdonate]